name: shivercovid
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
  - kantorlab
dependencies:
  - biopython=1.78
  - blast=2.9.0
  - bowtie2=2.3.5.1
  - bwa=0.7.17
  - cd-hit=4.8.1
  - fastq-tools=0.8
  - git=2.23.0
  - iqtree=2.0.3
  - kallisto=0.46.0
  - kraken2=2.0.8_beta
  - mafft=7.455
  - pandas=1.1.3
  - picard=2.18.29
  - pip=20.2.4
  - pyfastaq=3.17.0=py_2
  - python=3.7.6
  - samtools=1.9
  - smalt=0.7.6
  - trimmomatic=0.39
